### ISSUE TITLE
graphcool.yml should have required property 'stage'. missingProperty: stage

### ISSUE THREAD

**Issue by develomark** [supergraphql/graphql-cli-prepare#23]
Hi Kim,

When running `graphql prepare` I am getting the following error:

```
 yaml {"missingProperty":"stage"} +0ms

[ERROR] in graphcool.yml:
graphcool.yml should have required property 'stage'. missingProperty: stage
```

If I add in 

```
stages:
  default: dev
  dev: local
```

I get the following error:
```
[ERROR] in graphcool.yml:
graphcool.yml should NOT have a "stages" property anymore. Stages are now just provided as CLI args.
Read more here: https://goo.gl/SUD5i5
```

versions:
    "graphql-cli": "^2.3.0",
    "graphql-cli-prepare": "^1.4.2",
    "graphcool": "1.0.0-beta2.1.1" -> global

Many thanks,
Mark

**Comment by kbrandwijk** [comment]
Thank you for reporting, but this error is related to the Graphcool part. There was an issue in the main Graphcool repo about it: https://github.com/graphcool/framework/issues/1458#issuecomment-354685314. If you run into any issues regarding this, please add a comment or open a new issue there.

**Comment by develomark** [comment]
Thanks Kim -> I'll check this out.
